name: ngalah_mobile
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
    
  # State management
  provider: ^6.1.2

  # HTTP client
  dio: ^5.6.0

  # Penyimpanan lokal (token/login, setting)
  shared_preferences: ^2.2.3

  # Untuk menampilkan SVG (kalau logo/icon SVG)
  flutter_svg: ^2.0.10+1

  # Format tanggal/waktu (contoh “Selamat Pagi” dinamis)
  intl: ^0.19.0
 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Untuk icon launcher app
  flutter_launcher_icons: ^0.13.1

  # Untuk splash screen otomatis
  flutter_native_splash: ^2.4.1


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_ngalah.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo_ngalah.png   # logo sesuai desain preopening
  android: true
  ios: true
